import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ? title + "- Amazona" : "Amazona"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <nav className="flex h-12 justify-between">
            <Link href="/">
              <a>amazona</a>
            </Link>
            <div>
              <Link href="/cart">Cart</Link>
              <Link href="/Login">Login</Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer>footer</footer>
      </div>
    </>
  );
}
